### ISSUE TITLE
External IDP metadata path in SAML

### ISSUE THREAD

**Issue by vgaur** [bujiio/buji-pac4j#55]
Hi,
Mine is a window server and I am using SAML2Client for authentication. I kept my idp metadta on a particular path on disk and specified that path say ( C:\\XYZ\\idp.xml) in SAML2ClientConfiguration.

in `org.pac4j.core.util.CommonHelper. extractPrefix()` its assumes the prefic as 'C' and which is causing the following exception.

>  org.pac4j.core.exception.TechnicalException: prefix is not handled:C

If we can add file prefix instead of assuming null prefix as file should solve the problem.

**Comment by leleuj** [comment]
Good catch! Things will be better in pac4j v2.0, but there is an issue with Windows currently. Can you use `file:C:\XYZ\idp.xml` instead? It should work. Thanks.

**Comment by vgaur** [comment]
Thanks @leleuj , even using `le:C:\XYZ\idp.xml` would cause the same problem, as switch condition inside `CommonHelper.getInputStreamFromName` will again throw the same exception. 
` org.pac4j.core.exception.TechnicalException: prefix is not handled:file`

In getFileName method inside Resource its handled but not handled in getInputStream.

Should I extend SAML2Client and handle SAML2IdentityProviderMetadataResolver inside it ?

**Comment by leleuj** [comment]
It's a bug we could handle fairly easily in pac4j 1.9.7: tracked here: https://github.com/pac4j/pac4j/issues/830

**Comment by leleuj** [comment]
Here is the proposed fix: https://github.com/pac4j/pac4j/pull/831

**Comment by leleuj** [comment]
It should be fixed in the 1.9.7-SNAPSHOT version: can you confirm the fix?

**Comment by vgaur** [comment]
Thanks @leleuj , yes its fixed.

**Comment by leleuj** [comment]
Cool! I'll release version 1.9.7 in a few weeks. Ping me if it's too long for you.

**Comment by simireddi** [comment]
Hi Leleuj - We are working of Jenkins 2.60 with SAML plugin 1.0.4. It has pac4j version org.pac4j:pac4j-saml:1.9.9 and this issue still exists. We had to use the fix that you suggested above (using File before the location) to get encryption working. It was very misleading since this is supposed to be fixed in version 1.9.7 and Jenkins plugin we used had version 1.9.9. 

Could you explain why there is discrepancy or was this bug reintroduced in later versions. BTW we have Jenkins running on windows.

Thanks,
SR

**Comment by leleuj** [comment]
I don't remember exactly, but for sure, the version 2.0 which uses the Spring `Resource` component is supposed to have no issues with that.
We are currently developing pac4j v3.0 so I can only recommend upgrading to 2.1.0 to benefit from the latest fixes.

**Comment by simireddi** [comment]
What version of Jenkins do I need to use to get latest version of pac4j? I have got all latest updates on SAML plugin as of now and I’m running Jenkins 2.60.3.

**Comment by leleuj** [comment]
It looks like that even the latest Jenkins SAML plugin uses an old pac4j version: https://github.com/jenkinsci/saml-plugin/blob/master/pom.xml#L84
The plugin should be upgraded.

**Comment by simireddi** [comment]
Will that be something you guys raise with Jenkins community?

**Comment by leleuj** [comment]
I haven't been in touch with the Jenkins community, but generally, pac4j upgrades are easy. I'm willing to help them if ever they need me.

**Comment by simireddi** [comment]
Do you work with SAML plugin folks? Sorry trying to understand dynamics here. Seems like Jenkins is not aware that there is bug with this plugin and users like me are stuck with it when there is fix available.

**Comment by leleuj** [comment]
I think the right thing to do is to get in touch with the Jenkins guys and tell them there is a bug in the plugin. Then, they'll decide what they want to do and whether they want to upgrade or not. Given that I'm willing to assist in this upgrade.
